### ISSUE TITLE
ga only works on unweighted graphs

### ISSUE THREAD

**Issue by arnaudon** [GiulioRossetti/cdlib#155] opened 2021-05-03 20:56 UTC
**Describe the bug**
With weighted nx graphs, ga stalls because  l 52 of algorithms/internal/ga.py

**To Reproduce**
a graphs with weights not equal to 1

**Expected behavior**
I don't know this algorithm well enough to see if there is a weighted version of it, but I think there should be a step to remove weights and warn the user.

**Comment by GiulioRossetti** [comment] 2021-05-05 06:50
Hi,
I tested with synthetic weighted graphs and was unable to reproduce the issue.
Can you provide a minimal code example to replicate it?

As a preliminary check, it seems to me that the code line you referred 
`rand = np.random.randint(0, nodes_length)`
cannot be affected by the presence of edge weights since the only variable involved is an integer whose computation solely relies on graph nodes.

**Comment by GiulioRossetti** [comment] 2021-05-05 07:10
Hi, the bug has been fixed in the master branch.
The fix will be included in the next package release.

Giulio

**Closed** 2021-05-05 07:09 UTC
Labels: Correctness check request

**Comment by arnaudon** [comment] 2021-05-05 07:19
Thanks @GiulioRossetti ! Nice code btw, very useful! And thanks for such a quick action! I'll ping you again if I encounter any other issues! Have a nice day!
