### ISSUE TITLE
MemoryError at algorithms.big_clam

### ISSUE THREAD

**Issue by oiwilliam** [GiulioRossetti/cdlib#76] opened 2019-10-11 03:09 UTC
**Describe the bug**
I was unable to run the algorithms.big_clam algorithm in a graph with 2436844 edges, receiving a MemoryError.

**To Reproduce**
I'm instantiating my graph from a data frame with source, target and weight, and than trying to get the communities.

g = nx.from_pandas_edgelist(ds, 'source', 'target', 'weight')
coms = algorithms.big_clam(g, 500)

- CDlib version cdlib-0.1.7
- Operating System mac os 10.12.5
- Python version 3.6
- Version(s) of CDlib required libraries

**Additional context**
I'm using jupyter notebook

**Exception trace**
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-123-1161752e0744> in <module>
----> 1 coms = algorithms.big_clam(g, 500)

/opt/conda/lib/python3.6/site-packages/cdlib/algorithms/overlapping_partition.py in big_clam(g, number_communities)
    576     g = convert_graph_formats(g, nx.Graph)
    577 
--> 578     communities = BIGCLAM.big_Clam(g, number_communities)
    579 
    580     return NodeClustering(communities, g, "BigClam", method_parameters={"number_communities": number_communities}, overlap=True)

/opt/conda/lib/python3.6/site-packages/cdlib/algorithms/internal/BIGCLAM.py in big_Clam(graph, number_communities)
     76 
     77 def big_Clam(graph, number_communities):
---> 78     adj = nx.to_numpy_matrix(graph)
     79     F = train(adj, number_communities)
     80     F_argmax = np.argmax(F, 1)

/opt/conda/lib/python3.6/site-packages/networkx/convert_matrix.py in to_numpy_matrix(G, nodelist, dtype, order, multigraph_weight, weight, nonedge)
    446     return M
    447 
--> 448 
    449 def from_numpy_matrix(A, parallel_edges=False, create_using=None):
    450     """Returns a graph from numpy matrix.

/opt/conda/lib/python3.6/site-packages/networkx/convert_matrix.py in to_numpy_array(G, nodelist, dtype, order, multigraph_weight, weight, nonedge)
   1125                     # This occurs when there are fewer desired nodes than
   1126                     # there are nodes in the graph: len(nodelist) < len(G)
-> 1127                     pass
   1128 
   1129     A[np.isnan(A)] = nonedge

/opt/conda/lib/python3.6/site-packages/numpy/core/numeric.py in full(shape, fill_value, dtype, order)
    300     shape : int or sequence of ints
    301         Shape of the new array, e.g., ``(2, 3)`` or ``2``.
--> 302     fill_value : scalar
    303         Fill value.
    304     dtype : data-type, optional

MemoryError:

**Comment by GiulioRossetti** [comment] 2019-10-11 10:09
The BigClam implementation is mutuated by the one available [here](https://github.com/RobRomijnders/bigclam).

Please contact the original author for a more precise fix.

**Comment by Yquetzal** [comment] 2019-10-11 10:27
If I'm right the problem come from our interface, from the line  
`nx.to_numpy_matrix`
That might require huge amount of memory for nodes with many nodes.
We might try `to_scipy_sparse_matrix` instead, but I'm not sure bigclam accept this format, Giulio could you check if it works ? otherwise I'll check this WE

**Comment by GiulioRossetti** [comment] 2019-10-11 11:11
You are right my bad, I didn't notice the transformation dependency.
I have to check but, it is likely that this implementation of bigclam does not accept sparse scipy matrices... I'll try to figure it out next week.

**Comment by GiulioRossetti** [comment] 2019-10-11 11:55
Update: the vanilla implementation of bigclam we use needs to be revised in order to support scipy sparse matrices. It can be done: the major effort is in rewriting the log-likelihood function I guess.

**Comment by Yquetzal** [comment] 2019-10-13 15:59
I tried rewriting the code to accept sparse matrices. It solves the initial memory issue, but then another memory issue arises later (some of the matrices created in the process are not sparse). It could be solved too, but I think it is not worth it: the code is too slow anyway to run on large graphs, because it is implemented by processing each node in a loop, which is (according to the author himself) inefficient. 
I check if we could add the original implementation, but it's only available in C. We could easily write a wrapper, but it would require the user to download and compile the snap library manually anyway, which was not the original idea of cdlib.
What we should do: Add a disclaimer if the size of the network is above 100k, that this implementation is not scalable. 
What we could do: Offer the possibility to run the original code, explaining how to install the c++ library. Is it worth it ?

**Comment by GiulioRossetti** [comment] 2019-10-13 17:16
I think we can indeed provide a wrapper for the original C implementation (as a low priority task). We already did something similar for some other algorithms (see infomap or SMB).

However, for the moment I would say that we can stick with a disclaimer on the method documentation.

**Comment by benman1** [comment] 2020-02-03 15:35
Hi. I've come across your paper. I am really impressed by the number of algorithms, however, I have a similar problem to the original post author: I have a big adjacency matrix in a sparse format (boolean lil_matrix). It just fills nearly all of my memory, and I am not exactly sure what to do. I've searched your documentation for _sparse_ but haven't found anything. Could you tell me (if any) which algorithms support sparse (or especially lil_matrix) formats? Is there a way the algorithms would directly work on the adjacency matrix without having to construct a graph?

**Comment by Yquetzal** [comment] 2020-02-03 15:52
Thanks for the question, I'm trying a first answer: The problem is not so much in the representation but in the fact that the big_clam algorithm integrated in the library is not an optimized version, so it cannot handle large graphs. Do you want to apply this algorithm in particular or several ones? The library is mostly designed to handle small to medium large graphs (<1Millions edges, I would say). 
Some algorithms might be more efficient than others...  But if your goal is to apply big clam on a very large graph, I think that our library won't solve your problem in its current form.

**Comment by benman1** [comment] 2020-02-03 16:09
Thanks for answering - much appreciated. I don't mind the algorithm really at this point; I am just trying to find something that would work with a large adjacency matrix, even if it's very simple, preferably without copying. At full it would be on the order of at least 100 million edges (i.e. nonzero edges); I am already at the point of downsampling the original dataset, which is a bit sad. Could you recommend something perhaps?

**Comment by Yquetzal** [comment] 2020-02-03 16:21
I think that you need to use software adapted to run on such graphs, A few references: The official implementation of the Louvain algorithm: https://sourceforge.net/projects/louvain/ 
Louvain using neo4j https://neo4j.com/blog/graph-algorithms-neo4j-louvain-modularity/
The snap library is also designed to be efficient and has some algorihtms: https://snap.stanford.edu

**Comment by benman1** [comment] 2020-02-03 16:25
Thank you very much! That's very helpful.

**Comment by GiulioRossetti** [comment] 2020-02-03 16:25
Hi @benman1, tbh I changed the implementation of big_clam a couple of days ago, including the one from the karateclub library. It seems to be more efficient than the one we had in the first place but I haven't tested on very big network I'm afraid. If you don't have the latest version (v.0.1.8) try updating cdlib and let me know. 

For networks of that sizes, I would go for algorithms implemented in C (either, snap or graph-tools) that properly handle memory management.

**Comment by benman1** [comment] 2020-02-03 16:35
Thanks again. Yes, both run-time and memory usage are a problem for me. I'll try out the big_clam algorithm. 

I've found [scipy's graph functionality](https://docs.scipy.org/doc/scipy-0.16.1/reference/sparse.csgraph.html). I will play around with this as well (or I might have to put something together myself - I hope it doesn't come to that).

**Comment by Yquetzal** [comment] 2020-02-13 07:58
Since we identified the problem, and we added a new implemention by integrating the karate club library, I close the issue.

**Closed by Yquetzal** 2020-02-13 07:58 UTC
Labels: bug
