### ISSUE TITLE
Compatibility issue with python3.8?

### ISSUE THREAD

**Issue by anthonimes** [GiulioRossetti/cdlib#118] opened 2020-06-21 09:22 UTC
Hello! 

I just tried using CDlib, from a pip installation on kubuntu (python3.8 as mentioned in the title). 
When importing algorithms from cdlib, I get the following error: 

`ImportError: cannot import name 'clock' from 'time' (unknown location)`

It seems that `clock` is deprecated in python3.8. 
Is python3.8 incompatible with CDlib? Or am I doing something wrong? 

Thanks a lot! 
Anthony

**Comment by GiulioRossetti** [comment] 2020-06-21 13:20
The issue is with some cdlib dependencies, not with cdlib itself unfortunately. The fix is integrated on the master branch but not yet ported in the pip package: try with a fresh install from GitHub.

**Comment by anthonimes** [comment] 2020-06-22 08:13
Thanks for your prompt answer! 
I tried a fresh install from GitHub, but still got the same issue. 

More precisely, i have `Successfully installed cdlib-0.1.8`. 
The optional requirements failed on several packages, but I am not sure this is relevant?

**Comment by GiulioRossetti** [comment] 2020-06-22 11:43
Try to upgrade the pulp library with

`pip install pulp==2.1`

This should solve your issue.
Let me know if it worked!

**Comment by anthonimes** [comment] 2020-06-22 14:35
This worked, thanks! 
Just a final remark, I got the following:
`ERROR: cdlib 0.1.8 has requirement pulp==1.6.*, but you'll have pulp 2.1 which is incompatible.` 

which I believe to be an outdated error message? :) 

Thanks again,

**Comment by GiulioRossetti** [comment] 2020-06-22 14:41
Exactly. 
I pushed the fix in the requirements only on the master branch, not in the PyPI package for now :)

**Closed** 2020-06-22 14:41 UTC
