### ISSUE TITLE
AttributeError in crisp_partition.py

### ISSUE THREAD

**Issue by iglesiasignacio** [GiulioRossetti/cdlib#222] opened 2023-06-25 22:23 UTC
**Describe the bug**
Some community detection algorithms (e.g. surprise_communities) fail when calling crisp_partition.py even running the examples in the docs

**To Reproduce**
I'm running this in Google Colab
```{python}
!pip install cdlib
# example from the docs
from cdlib import algorithms
import networkx as nx
G = nx.karate_club_graph()
coms = algorithms.surprise_communities(G)
```

**Full traceback**
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-1-49c0388a8ce2>](https://localhost:8080/#) in <cell line: 6>()
      4 import networkx as nx
      5 G = nx.karate_club_graph()
----> 6 coms = algorithms.surprise_communities(G)

[/usr/local/lib/python3.10/dist-packages/cdlib/algorithms/crisp_partition.py](https://localhost:8080/#) in surprise_communities(g_original, initial_membership, weights, node_sizes)
    991     g = convert_graph_formats(g_original, ig.Graph)
    992 
--> 993     part = leidenalg.find_partition(
    994         g,
    995         leidenalg.SurpriseVertexPartition,

AttributeError: 'NoneType' object has no attribute 'find_partition'
```

**Comment by GiulioRossetti** [comment] 2023-06-26 12:38
Hi,

Fortunately, the issue is straightforward to address. 
It seems you don't have the `leidenalg` package installed (it's among the optional dependencies since it relies on C code): install it (pip install leidenalg) and everything will work fine.

I updated the import check in `crisp_partition.py`: the fix will be integrated into the next release of the library.

**Closed** 2023-06-28 16:04 UTC
